- name: install apache2
  package: 
    name: apache2
    state: present
    update_cache: yes
  environment: "{{ proxy_env }}"

- name: enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
    ignore_configcheck: yes
  notify:
    - restart apache2

- name: remove index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: copy index.php 
  copy:
    src: files/index.php
    dest: /var/www/html/
    mode: 0644 