- name: add vscode key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  environment: "{{ proxy_env2 }}"

- name: add vscode repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  environment: "{{ proxy_env }}"

- name: install dependencies
  package: 
    name: apt-transport-https
    state: present
    update_cache: yes
  environment: "{{ proxy_env }}"  

- name: install vscode
  package:
    name: code
    state: present
    update_cache: yes
  environment: "{{ proxy_env }}"