- name: install chrome using deb package
  package:
    deb: http://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_70.0.3538.77-1_amd64.deb
  environment: "{{ proxy_env }}"